### ISSUE TITLE
Question on building from source

### ISSUE THREAD

**Issue by pattty847** [Tucsky/aggr#248]
Hey, 

I wasn't sure where I could post this so I apologize if this is the incorrect area. In the past I had no problems building from source and running the build but this time after running:
```npm install```

I get numerous errors. I googled around and it seems like the lockfile was generated with a different version of npm. I'm not too good a Javascript so I'm a bit unsure how to either change my npm or fix these issues.

To recreate the issue, all I did was **clone from command line** using the normal readme file included. Then ran the **npm install** command which game me the errors. 

I've tried these commands as well:
```
npm audit fix
npm audit fix --force
```

Errors after install command.
```
npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:738:24)
npm WARN old lockfile  Could not fetch metadata for fork-ts-checker-webpack-plugin-v5@5.2.1 fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:738:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '5.2.1',
npm WARN old lockfile   versions: [ '0.0.1-security' ],
npm WARN old lockfile   distTags: { latest: '0.0.1-security' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:738:24)
npm WARN old lockfile  Could not fetch metadata for vue-loader-v16@16.8.3 vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (C:\Users\pattt\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:738:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '16.8.3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '16.0.0-beta.5',
npm WARN old lockfile     '16.0.0-beta.5.1',
npm WARN old lockfile     '16.0.0-beta.5.2',
npm WARN old lockfile     '16.0.0-beta.5.3',
npm WARN old lockfile     '16.0.0-beta.5.4'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1844 packages, and audited 1845 packages in 8m

128 packages are looking for funding
  run `npm fund` for details

35 vulnerabilities (5 moderate, 21 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run npm audit for details.

C:\Users\pattt\Desktop\Programming\aggr>npm audit
# npm audit report

ejs  <3.1.7
Severity: critical
ejs template injection vulnerability - https://github.com/advisories/GHSA-phwq-j96m-2c2q
fix available via `npm audit fix --force`
Will install @vue/cli-service@5.0.8, which is a breaking change
node_modules/ejs
  webpack-bundle-analyzer  1.3.0 - 3.9.0
  Depends on vulnerable versions of ejs
  node_modules/@vue/cli-service/node_modules/webpack-bundle-analyzer
    @vue/cli-service  <=5.0.0-rc.3
    Depends on vulnerable versions of @intervolga/optimize-cssnano-plugin
    Depends on vulnerable versions of @vue/cli-plugin-router
    Depends on vulnerable versions of @vue/cli-plugin-vuex
    Depends on vulnerable versions of copy-webpack-plugin
    Depends on vulnerable versions of cssnano
    Depends on vulnerable versions of globby
    Depends on vulnerable versions of webpack-bundle-analyzer
    Depends on vulnerable versions of webpack-dev-server
    node_modules/@vue/cli-service
      @vue/cli-plugin-babel  4.0.0-alpha.0 - 4.5.19
      Depends on vulnerable versions of @vue/cli-service
      node_modules/@vue/cli-plugin-babel
      @vue/cli-plugin-eslint  3.1.2 - 5.0.0-rc.3
      Depends on vulnerable versions of @vue/cli-service
      Depends on vulnerable versions of globby
      node_modules/@vue/cli-plugin-eslint
      @vue/cli-plugin-pwa  4.0.0-alpha.0 - 4.5.19
      Depends on vulnerable versions of @vue/cli-service
      node_modules/@vue/cli-plugin-pwa
      @vue/cli-plugin-router  <=4.5.19
      Depends on vulnerable versions of @vue/cli-service
      node_modules/@vue/cli-plugin-router
      @vue/cli-plugin-typescript  <=5.0.0-rc.3
      Depends on vulnerable versions of @vue/cli-service
      Depends on vulnerable versions of globby
      node_modules/@vue/cli-plugin-typescript
      @vue/cli-plugin-vuex  <=4.5.19
      Depends on vulnerable versions of @vue/cli-service
      node_modules/@vue/cli-plugin-vuex

glob-parent  <5.1.2
Severity: high
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install @vue/cli-service@5.0.8, which is a breaking change
node_modules/copy-webpack-plugin/node_modules/glob-parent
node_modules/fast-glob/node_modules/glob-parent
node_modules/watchpack-chokidar2/node_modules/glob-parent
node_modules/webpack-dev-server/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
  node_modules/webpack-dev-server/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack
    webpack-dev-server  2.0.0-beta - 4.7.2
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of selfsigned
    node_modules/webpack-dev-server
  copy-webpack-plugin  5.0.1 - 5.1.2
  Depends on vulnerable versions of glob-parent
  node_modules/copy-webpack-plugin
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/globby

jpeg-js  <0.4.4
Severity: high
Infinite loop in jpeg-js - https://github.com/advisories/GHSA-xvf7-4v9q-58w6
fix available via `npm audit fix`
node_modules/jpeg-js
  @jimp/jpeg  <=0.12.0 || 0.16.1 - 0.16.2-canary.1094.1345.0
  Depends on vulnerable versions of jpeg-js
  node_modules/@jimp/jpeg

node-forge  <=1.2.1
Severity: high
Open Redirect in node-forge - https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
Prototype Pollution in node-forge debug API. - https://github.com/advisories/GHSA-5rrq-pxf6-6jx5
Improper Verification of Cryptographic Signature in `node-forge` - https://github.com/advisories/GHSA-2r2c-g63r-vccr
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-x4jg-mjrx-434g
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-cfm4-qjh2-4765
URL parsing in node-forge could lead to undesired behavior. - https://github.com/advisories/GHSA-gf8q-jrpm-jvxq
fix available via `npm audit fix --force`
Will install @vue/cli-service@5.0.8, which is a breaking change
node_modules/node-forge
  selfsigned  1.1.1 - 1.10.14
  Depends on vulnerable versions of node-forge
  node_modules/selfsigned

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install vue-svg-loader@0.10.0, which is a breaking change
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      postcss-svgo  4.0.0-nightly.2020.1.9 - 5.0.0-rc.2
      Depends on vulnerable versions of svgo
      node_modules/postcss-svgo
        cssnano-preset-default  <=4.0.8
        Depends on vulnerable versions of postcss-svgo
        node_modules/cssnano-preset-default
          @intervolga/optimize-cssnano-plugin  >=1.0.2
          Depends on vulnerable versions of cssnano
          Depends on vulnerable versions of cssnano-preset-default
          node_modules/@intervolga/optimize-cssnano-plugin
          cssnano  4.0.0-nightly.2020.1.9 - 4.1.11
          Depends on vulnerable versions of cssnano-preset-default
          node_modules/cssnano
      svg-to-vue  *
      Depends on vulnerable versions of svgo
      node_modules/svg-to-vue
        vue-svg-loader  0.11.0 - 0.16.0
        Depends on vulnerable versions of svg-to-vue
        node_modules/vue-svg-loader

postcss  <7.0.36
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install svg-sprite-loader@2.0.3, which is a breaking change
node_modules/svg-baker/node_modules/postcss
  svg-baker  >=1.2.5
  Depends on vulnerable versions of postcss
  node_modules/svg-baker
    svg-baker-runtime  >=1.4.0-alpha.10475b37
    Depends on vulnerable versions of svg-baker
    node_modules/svg-baker-runtime
      svg-sprite-loader  >=2.0.4
      Depends on vulnerable versions of svg-baker
      Depends on vulnerable versions of svg-baker-runtime
      node_modules/svg-sprite-loader

35 vulnerabilities (5 moderate, 21 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by Tucsky** [comment]
I do not see any error in the log you posted
After `npm install` simply run `npm run serve` or `npm run build`

**Comment by pattty847** [comment]
> I do not see any error in the log you posted After `npm install` simply run `npm run serve` or `npm run build`

Thanks for your reply.

One note. The difference between when I posted this and now is I installed Vue globally which gave me a different error than before when I ran `npm run build` before. 

I can run the `npm run serve` command which gives me a window full of the files as boxes I can zoom in on.

This is my error now for `npm run build`: 

```
C:\Users\pattt\Desktop\Programming\aggr>npm run build
[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
> aggr@3.2.0 build
|  Building for production...[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

/  Building for production...[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

\  Building for production...

 WARNING  Compiled with 2 warnings                                                                           12:14:22 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/chunk-vendors.df82bc5b.js (350 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (645 KiB)
      js/chunk-vendors.df82bc5b.js
      css/app.272bc4b3.css
      js/app.bc4c8796.js


Webpack Bundle Analyzer saved report to C:\Users\pattt\Desktop\Programming\aggr\dist\report.html
  File                                                          Size                       Gzipped

  dist\js\chunk-vendors.df82bc5b.js                             350.30 KiB                 106.84 KiB
  dist\js\app.bc4c8796.js                                       232.99 KiB                 63.95 KiB
  dist\js\chunk-00f8fb9c.e72c81a7.js                            164.81 KiB                 47.35 KiB
  dist\js\chunk-73666f02.1a69c1db.js                            159.61 KiB                 47.44 KiB
  dist\js\chunk-662f5aef.c34ac558.js                            93.95 KiB                  25.50 KiB
  dist\js\aggregator.32a5e2d4.worker.js                         89.04 KiB                  25.45 KiB
  dist\js\chunk-2d0cc844.3183866d.js                            81.95 KiB                  26.11 KiB
  dist\js\chunk-48f0107b.dc0cf54d.js                            54.63 KiB                  12.24 KiB
  dist\js\chunk-03130df0.c365bfda.js                            32.14 KiB                  11.69 KiB
  dist\js\chunk-1e0e1a87.d0da451f.js                            29.87 KiB                  7.63 KiB
  dist\js\chunk-5c268662.1384ff03.js                            21.38 KiB                  6.79 KiB
  dist\js\chunk-d2fbbe60.c554081e.js                            20.39 KiB                  7.41 KiB
  dist\js\chunk-ebc5e646.e1e7a10e.js                            14.10 KiB                  3.90 KiB
  dist\js\chunk-3bbacbcd.5deea3d4.js                            12.80 KiB                  4.11 KiB
  dist\js\chunk-3c639b53.9ddd8c71.js                            12.25 KiB                  3.71 KiB
  dist\js\chunk-3a77d76f.6f0ae699.js                            11.32 KiB                  4.14 KiB
  dist\js\chunk-1e3ac1a1.4d720fe4.js                            9.32 KiB                   3.00 KiB
  dist\js\chunk-1d61eeb5.a17341d5.js                            8.74 KiB                   2.89 KiB
  dist\js\chunk-653050d6.52231507.js                            5.94 KiB                   1.81 KiB
  dist\precache-manifest.503a9154358fe5b84ee42bc85e7a2e21.js    5.65 KiB                   1.70 KiB
  dist\js\chunk-10024d20.68b4f063.js                            4.71 KiB                   1.73 KiB
  dist\sw.js                                                    4.66 KiB                   1.84 KiB
  dist\js\chunk-2f4fd947.cfe5b6d9.js                            4.60 KiB                   1.92 KiB
  dist\js\chunk-6edad2a6.0ab054a3.js                            4.12 KiB                   1.68 KiB
  dist\service-worker.js                                        1.03 KiB                   0.60 KiB
  dist\css\app.272bc4b3.css                                     62.06 KiB                  12.30 KiB
  dist\css\chunk-5c268662.2e1164cc.css                          16.16 KiB                  5.75 KiB
  dist\css\chunk-3c639b53.6de0bf14.css                          12.88 KiB                  4.93 KiB
  dist\css\chunk-662f5aef.3a3e7136.css                          4.97 KiB                   1.39 KiB
  dist\css\chunk-1e0e1a87.22f03d2a.css                          4.25 KiB                   1.17 KiB
  dist\css\chunk-48f0107b.52743c60.css                          3.94 KiB                   1.22 KiB
  dist\css\chunk-3a77d76f.5cdb843c.css                          1.60 KiB                   0.58 KiB
  dist\css\chunk-3bbacbcd.058181ef.css                          0.89 KiB                   0.43 KiB
  dist\css\chunk-1e3ac1a1.dbf034c7.css                          0.87 KiB                   0.43 KiB
  dist\css\chunk-ebc5e646.903252b6.css                          0.43 KiB                   0.19 KiB
  dist\css\chunk-1d61eeb5.6dc9840e.css                          0.31 KiB                   0.20 KiB
  dist\css\chunk-03130df0.8dbd7c45.css                          0.09 KiB                   0.10 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

**Comment by pattty847** [comment]
> I do not see any error in the log you posted After `npm install` simply run `npm run serve` or `npm run build`

Tucsky, 

After installing Vue globally and following the link for running the dist I was able to get it to work. 

Thanks for your response and creating the app.
