### ISSUE TITLE
"aggr" just blew up in Windows Power Shell

### ISSUE THREAD

**Issue by DROBNJAK** [Tucsky/aggr#288]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- [ ] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
- [ ] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
- [ ] I documented the issue with screenshots
- [ ] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

...

### Steps to reproduce

(Preferably from a clean environment / incognito mode)
1. TODO
2. TODO
3. TODO
...

**Comment by DROBNJAK** [comment]
PS C:\tmp\aggr> npm run serve

> aggr@3.3.1 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...C:\tmp\aggr\node_modules\eslint-loader\index.js??ref--14-0!C:\tmp\aggr\src\main.tsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\tmp\aggr\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\tmp\aggr\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0

**Comment by Tucsky** [comment]
looks like you just need to [downgrade nodejs](https://stackoverflow.com/a/69699772)

**Comment by adeacetis** [comment]
It is not necessary to downgrade your `nodejs`. This is happening because NodeJS >= 17 introduced OpenSSL 3.

![image](https://user-images.githubusercontent.com/20586054/224960776-5c899329-7852-4c4b-97ea-884f066f1600.png)

You can run this prefix before all your npm scripts and you'll do fine:
`set NODE_OPTIONS=--openssl-legacy-provider &&`

![image](https://user-images.githubusercontent.com/20586054/224957661-b5df0eb4-9539-4676-b8b6-f6cb1c3f380a.png)

However, note that one deep dependency doesn't do well with Node being above 14. I've been investigating this.

Edit your package.json accordingly.

**Comment by DROBNJAK** [comment]
First I did what you suggested first. There was an improvement and server kicked in, but it eventually failed ( on Win 10 ): 

PS C:\tmp\aggr> set NODE_OPTIONS=--openssl-legacy-provider
PS C:\tmp\aggr> npm run serve

> aggr@3.3.1 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/3 modules 1 active ...C:\tmp\aggr\node_modules\eslint-loader\index.js??ref--14-0!C:\tmp\aggr\src\main.tsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\tmp\aggr\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active C:\tmp\aggr\node_modules\webpack\hot\dev-server.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\tmp\aggr\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\tmp\aggr\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\tmp\aggr\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\tmp\aggr\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\tmp\aggr\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}


So, I run a second attempt, where I changed my "package.json" file according to your instructions in the above snippet. This time it failed immediately, with these messages:

PS C:\tmp\aggr> set NODE_OPTIONS=--openssl-legacy-provider
PS C:\tmp\aggr> npm run serve

> aggr@3.3.1 serve
> set NODE_OPTIONS=--openssl-legacy-rovider && vue-cli-service serve

node: --openssl-legacy-rovider is not allowed in NODE_OPTIONS

**Comment by DROBNJAK** [comment]
Please, let me know if you have any more ideas, because I hate downgrading.

But, in the worst case, what is the lowest downgrade version that will be safe?

**Comment by adeacetis** [comment]
I also tried to do that manually but it didn't work. You have to edit the `npm run serve` script located in `package.json` as proposed above.
Should look like this right now:
```
  "scripts": {
    "serve": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
    "prod": "set NODE_OPTIONS=--openssl-legacy-provider  && vue-cli-service build --dest ./temp && rm -rf ./dist && mv ./temp ./dist",
    "build": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build",
    "lint": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service lint",
    "deploy": "node scripts/gh-pages-deploy.js --openssl-legacy-provider"
  },
```

**Comment by Tucsky** [comment]
Next time consider using [Volta](https://volta.sh/) for managing node versions
It takes the version used by the project, and will install it for you as soon as you run a node command (or npm)
Here I use node 10

**Comment by adeacetis** [comment]
@Tucsky I tried to run some tests to see where we could 'safely' upgrade the app.

Installed the project using `node@18.5` and got this `warn` message.
![image](https://user-images.githubusercontent.com/20586054/224965459-9bcb4823-443a-43c9-ad77-ad23ef4b05cb.png)

I have investigated a bit further and that dependency is being imported in `@vue/cli-shared-utils` which in turn is used to create a communication pipe between vue and `webpack-dashboard`. The latter is used to display information in the console when we build/serve the repo.

But since it's packed with Vue 2.x. We're stuck there. It's interesting to notice that when you use Node 17, other dependencies start to complain about the engine version requiring only LTS ones which means 14, 16, or 18.

Therefore, I am concluding that we're stuck using Node 16 for the time being.
